language: ruby
arch:
  - amd64
  - ppc64le
rvm:
  - 2.5.3
  - 2.6.1
  - jruby-9.2.0.0
  - ruby-head
  - jruby-head

before_install:
  - gem update --system

env:
  global:
    - JRUBY_OPTS=--dev

script:
  - bundle exec rake ${TEST_SUITE:-test}

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9.2.0.0
    - env: TEST_SUITE=templates:test
# ppc64le support code
    - rvm: ruby-head
      arch: ppc64le
    - rvm: jruby-head
      arch: ppc64le
    - rvm: jruby-9.2.0.0
      arch: ppc64le
    - env: TEST_SUITE=templates:test
      arch: ppc64le
  include:
    - env: TEST_SUITE=templates:test
      rvm: 2.6.1
    - env: TEST_SUITE=templates:test
      arch: ppc64le
      rvm: 2.6.1
